version: '3'
services:
  lmntal:
    image: lmntal
    hostname: lmntal-host
    build: .
    command: java -jar LaViT.jar
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=:0